### ISSUE TITLE
cannot read zip_data file from script folder

### ISSUE THREAD

**Issue by ksiddana** [codeforsanjose/OpenDSJ-2018#1]
Downloaded the zip data from https://www.census.gov/geo/maps-data/data/cbf/cbf_zcta.html, used the python file in the script on the file, got the following error:
```  
File "zip_code_extractor.py", line 101, in <module>
    raise FileNotFoundError(settings.zip_data)
FileNotFoundError: None```

**Comment by ksiddana** [comment]
Downloaded the zip data from https://www.census.gov/geo/maps-data/data/cbf/cbf_zcta.html, used the python file in the script on the file, got the following error:
```  
File "zip_code_extractor.py", line 101, in <module>
    raise FileNotFoundError(settings.zip_data)
FileNotFoundError: None```

**Comment by matthewnorman** [comment]
So usually this implies that the file was put in incorrectly. Can you tell me what the command line code was?
