### ISSUE TITLE
Find data on CA Controller candidates (Nov 6, 2018 General Election)

### ISSUE THREAD

**Issue by lilannie** [codeforsanjose/OpenDSJ-2018#20]
Lol I did not know "Controller" was a position in the government.

Get campaign finance (and general) information on:
1. Betty T. Yee
2. Konstantinos Roditis

**Contribution Dates** 
Don't get data for all elections, just Nov 6, 2018 General Election. We think that means contributions from 2017-2018. Or try to see if the data portal you are looking at, as a filter for "Nov 6, 2018 General Election"

Things to base your research off of:
https://www.opendisclosure.io

Vision:
Ideally, we would like to find a general API we could use to pull campaign finance and general candidate information for any candidate.
However, given the fast approaching November 2018 election, we might have to hard code the data this run around.
If we have to hardcode all the data, we can go back to make the data consumption more automated and scalable.

I got the list of candidates from this link:
https://elections.cdn.sos.ca.gov/statewide-elections/2018-general/contact-list.pdf

**Comment by lenatran** [comment]
I can look into this
