### ISSUE TITLE
Find data on Attorney General

### ISSUE THREAD

**Issue by lilannie** [codeforsanjose/OpenDSJ-2018#22]
Get campaign finance (and general) information on:
1. Xavier Becerra (Democrat)
2. Steven C Bailey (Republican)

Things to base your research off of:
https://www.opendisclosure.io

Vision:
Ideally, we would like to find a general API we could use to pull campaign finance and general candidate information for any candidate.
However, given the fast approaching November 2018 election, we might have to hard code the data this run around.
If we have to hardcode all the data, we can go back to make the data consumption more automated and scalable.

I got the list of candidates from this link:
https://elections.cdn.sos.ca.gov/statewide-elections/2018-general/contact-list.pdf

**Comment by ghost** [comment]
Hi @lilannie, would you please assign this issue to me? I've also added basic candidate info to your [Google Sheet](https://docs.google.com/spreadsheets/d/1ulWeOIdCrRJ237BCQaaiwhodoeWp21fTyvZYYL4pjeg/edit) and created a pull request with the CSVs from [Power Search](http://powersearch.sos.ca.gov/). Please let me know if this is sufficient, and I'll replicate for other issues. Thank you!

**Comment by ghost** [comment]
Just noticed that the CSV files had extra lines at the very end, e.g.

Search criteria used to create this report:
Contributor(s): All
Contributor State: All
Recipient(s): Candidate: THURMOND, TONY
Contribution Cycles: 2017

So I removed these lines, deleted the original files, and re-uploaded (along with two more files for issue #24). Thank you!

**Comment by lilannie** [comment]
@agnesoshiro Yes, I can assign you the issue after you accept the collaborator invitation. (:

Awesome job! Looks like really quality data. (: 

Please take a look at this issue when you get a chance: https://github.com/codeforsanjose/OpenDSJ-2018/issues/43
I would love your input.
