### ISSUE TITLE
Find campaign finance data on San Jose City City Council Elections (General Election Nov 6, 2018)

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/OpenDSJ-2018#32]
**Update:**
To download the data, go to SJC election campaign finance data portal: https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/

*Get the following forms for candidates for San Jose City Council D7 and D9 races by Friday Nov 2*

- [x] - Form 460
- [x] - Form 460-A
- [ ] - Form 461  
- [ ] - Form 496/497 

**Next steps:**
1) Download the XSL/CSV files, add them to the git repository on a new branch
2) Extract the important information from the XSL/CSV files you found by extracting the important information to a single JSON or XSL/CSV file. JSON preferred, so it's easier to extract the data.
3) Make a PR

**Comment by ychoy** [comment]
This is where you can access the SJC election files: https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/

**Comment by lilannie** [comment]
`I think it would be helpful for the new people, if we provide a list of candidates and measures they are suppose to target.`
Same thing.

**Comment by lilannie** [comment]
These are the only candidates I could find that are up for election this November in SJC:
http://sanjoseca.gov/DocumentCenter/View/79243

Are there more?

**Comment by ychoy** [comment]
@lilannie That looks correct. The primary election had more races, but according to SJC website: Candidates who received more than 50% of the vote in the June Primary are elected and will assume office on January 1, 2019. 

That's why for General Election there are only 2 San Jose City Council races remaining: D7 and D9.

This list has all the SCC candidates, including candidates that San Jose voters could participate in (school boards, other kinds of boards), but I think this would fall under #33 
https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/official%20candidate%20list.pdf 

Also, there are 4 San Jose specific measures: https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/List%20of%20Local%20Measures.pdf

I think the San Jose measure data might be collected by the SJC campaign data portal. I'm going to make a separate issue for that.

**Comment by ychoy** [comment]
Currently we have Form 460 (data only gets updated 2-3x a year). Also need to get:

Form 461 (filed by Independent Expenditure Committees) for any committees fundraising for city council candidates
Form 496/497: Within 90 days of the election, contributions and expenditures over $1000 must be reported within 24 hours on form 496/497.
Form 496/497 is tricky because items will be re-reported on the next Form 460.

**Comment by ychoy** [comment]
I'm working on updating these files

**Comment by ychoy** [comment]
I could not find any form 461, 497 for these candidates
