### ISSUE TITLE
Find data on Santa Clara County elections

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/OpenDSJ-2018#33]
**Update:**
To download the data, go to SCC election campaign finance data portal: https://public.netfile.com/pub2/?aid=SCC&AspxAutoDetectCookieSupport=1

*Which elections do we want to track?*
See this [doc about Nov 2018 candidates](https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/official%20candidate%20list.pdf) from **Page 6 (beginning with "Gavilan")** -34 are the SCC elections to focus on for this issue.  

See this [doc about Nov 2018 measures](https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/List%20of%20Local%20Measures.pdf)
- We want to pay attention to the non San Jose measures. I think the San Jose measures data is collected on the city's campaign website, so it will go in a separate issue

Reference [doc about Nov 2018 measures](https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/List%20of%20Local%20Measures.pdf)

**If you have the time, extract this data**
* Name of candidate /measure 
* Total Contributions:
(RCPT is a contribution made by others; LOAN refers to candidate loan, which should be distinguished from RCPT)
* Total Expenditures:
(EXPN is campaign expenses, which should be distinguished from RCPT and LOAN)
* Current balance
* Overall stats about Contributions: % out of state, % within X (district or city), % within California 
* A break down of total contributions with a list: Donor Name | Donor Occupation | Donor City | Donation Amount | Date of Donation 
* A break down of total expenditures  by category

**Otherwise just get all the data and combine into this format**
1) Download the XSL/CSV files on candidates and measures - FPPC Form 460 and Form 460 A (Amendment), add them to the git repository on a new branch
2) Combine the data into one XSL/CSV file per ballot measure/committee 
3) Turn the data in JSON

For reference take a look at PR #46

**Comment by ychoy** [comment]
SCC election campaign finance data portal: https://public.netfile.com/pub2/?aid=SCC&AspxAutoDetectCookieSupport=1

**Comment by lilannie** [comment]
I think it would be helpful for the new people, if we provide a list of candidates and measures they are suppose to target.

**Comment by lilannie** [comment]
I believe this is the list of Candidates for the Santa Clara County General Election:
https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/official%20candidate%20list.pdf

Here is a list of local measures:
https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/List%20of%20Local%20Measures.pdf

**Comment by lilannie** [comment]
```
SCC election campaign finance data portal: https://public.netfile.com/pub2/?aid=SCC&AspxAutoDetectCookieSupport=1
```

From what I found, the campaign finance from this data portal is recorded in PDF files. This is very problematic since I don't think any of us wants to parse the data manually.

**Comment by ychoy** [comment]
@lilannie  when I go to this [website](https://public.netfile.com/pub2/(X(1)S(ferlekywklyjjki4bqdwr3gj))/default.aspx?aid=SCC&AspxAutoDetectCookieSupport=1), near the top, you can download the excel (all files) for 2018, 2017, and so forth. It's awesome that they aggregate the data into one export file: 

Export E-Filed FPPC Form 460 - 496 - 497 - 461 - 465 transactions by year to Excel.
Select (by year)  **I think we need 2017 and 2018. I'm not sure if we need 2016**
Export Amended: Most Recently amended version of the transactions only
Export All: Original and all amended versions of the transactions
Note: These reports are updated overnight.

Download the Excel Export FAQ or the more extensive Excel Export Key.

**Comment by ychoy** [comment]
@lilannie I think the San Jose specific measures (listed in the link you mentioned above) is collected the SJC campaign data portal. I'm going to make it a separate issue.

**Comment by njavs** [comment]
I'm taking on Page 8 (starting with candidate KELLY YIP-CHUAN and ending with candidate WENDY SULLIVAN).

**Comment by ychoy** [comment]
FYI, if you use the Advanced Search, you may end up getting incomplete data? According to the website:

The Advanced Search for Transaction Data searches all transactions electronically filed on Fair Political Practices Commission (FPPC) forms 401, 450, 460, 461, 465, 496, 497 and 498.

Certain transactions from "late filed" or "supplemental filed" forms 465, 496, 497 and 498 will be displayed in these search results from each containing filing, and may appear to be duplicated. The "Filing ID" column will indicate the source of each reported transaction.

For a complete download of all e-filed transactions, including all original and amended transactions, use the "Export E-Filed Data" function on the Search Home page.

If you have any questions about what the headers mean, I've added the Data FAQ key document to our repo, under RESOURCES.

**Comment by ychoy** [comment]
I found the data for page 6 (detailed in issue #50) for SCC Board of Education Areas 2,6,7, see #54  PR for reference.  Basically before Gavillan. 

_Here is my process - if it helps:_
My process is to download the zip folder on the first first (Export Amended), find the candidate (if they exist as a filier, some do not have anything filed) for the A-contributions tab and E-expenditures tab, and then save the data in two files per candidate: A-contributions tab and E-expenditures. Then I wrote some scripts (see #54) to convert the xls files into JSON. 

How's it going for you @njavs @aeevrubin @abidishajia? I believe Grace Lee is working on Page 9, Nausheen is working on Page 8 (from KELLY YIP-CHUAN to WENDY SULLIVAN). 
**Can you please submit your PRs for data by tomorrow Wednesday 10/31 at 12pm?** 

To reiterate our goals from last meeting on 10/25:  
- [ ] get all the data, or as much as we can, for SJC and SCC candidates and measures by Monday Oct 29 
- [ ] figure out what format we need it to be in (or what to parse out). Annie and I are in communication with OpenDisclosure.io team to see what format they need and if they'll be able to work with our data if we are able to parse it all by Friday 11/2
- [ ] clean up the data Thursday 11/1
- [ ] share data with OpenDisclosure.io team so they can incorporate it into their existing site. If it is too short of timing for them, then we'll meet up Thursday 11/1 to determine what MVP data visualizations we can make with the existing data we have
- [ ] deployment! hopefully on OpenDisclosure.io by Sunday
- [ ] some social media marketing or other creative means so the public can know about this since election is 11/6! 

Thoughts?

**Comment by ychoy** [comment]
**Update:** Aaron from Opendisclosure.io team said that for the SCC data, since they are using Netfile, the same system Oakland uses, we won't have to get the data on SCC office elections/measures for them. Aaron can use an existing script to get the files on SCC measures. 

However, since City of SJ uses a different system, we do need to retrieve data from southtesthosting's website. Also, we don't just care about Form 460 (since that data only gets updated 2-3x a year), we also need to pay attention to:
- Form 461 (filed by Independent Expenditure Committees(
- Form 496/497: Within 90 days of the election, contributions and expenditures over $1000 must be reported within 24 hours on form 496/497. 

Form 496/497 is tricky because items will be re-reported on the next Form 460.

But for the SCC candidates and measures, we do not need to retrieve data to send to OpenDisclosure.io.

**Comment by njavs** [comment]
@ychoy To clarify, issue #33 no longer needs to be worked on?

**Comment by ychoy** [comment]
@njavs, yes, that's correct. 

The only data opendisclosure.io needs from us is #44 and #32. And ballot info #55, by this Friday Nov 2nd end of day.

By the way, Aaron from OpenDisclosure.io team said that they will try their best to integrate San José data into OpenDisclosure.io, but there's no guarantee they will get this done before the General Election (Nov 6,2018).
