### ISSUE TITLE
Set up Travis CI

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/OpenDSJ-2018#35]

**Comment by lilannie** [comment]
How do we plan on hosting the website?

**Comment by ychoy** [comment]
You mean for deployment? If it's heroku, it would be free? Not sure if we have AWS credits @3vivekb ? 

Also, website hosting - that could be a separate issue? Travis CI works on development projects too.

**Comment by lilannie** [comment]
We love free! I've never used Heroku. I'll leave those logistics up to you.

Can you give me a use case of Travis CI? I've never used it and am confused about how it fits into our project.

**Comment by ychoy** [comment]
Travis CI is for continuous integration. It automates the build. Every time you have new branch or PR, it will trigger the build. For example, you might have the following scripts: npm install, npm run lint, npm run test (if we have tests). If nothing crashes, then it will say that the build is passing. Why use Travis CI? So you can discover quickly if your commit broke something and fix it before it becomes a problem. 

It's also something common I've seen in open source projects. Not sure if it's considered best practice. I notice a lot of my DevOp engineer friends typically set up before doing anything else.
