### ISSUE TITLE
Find data on San Jose General Election Nov 6, 2018 - committees 

### ISSUE THREAD

**Issue by ychoy** [codeforsanjose/OpenDSJ-2018#44]
Reference [doc about Nov 2018 measures](https://www.sccgov.org/sites/rov/Info/Nov2018info/Documents/List%20of%20Local%20Measures.pdf)

Get data from 
[https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/Search/SearchByBallotItem.aspx](link)
*Get data for the Ballot Items Measure S, T, U, V,;General Purpose, Major Donor, City Council District 7:*
Form 460
Form 460-A
Form 461  
Form 496/497 

If there is any data, we should try to get it uploaded.
 
You can get the data on [SJC campaign data portal](https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/Search/SearchByElection.aspx) -- look up files for General Election Nov 6, 2018, and download all Form 460 and Form 460-A related to committees supporting/against ballot measures

**If you have the time, extract this data**
* Name of candidate /measure 
* Total Contributions:
(RCPT is a contribution made by others; LOAN refers to candidate loan, which should be distinguished from RCPT)
* Total Expenditures:
(EXPN is campaign expenses, which should be distinguished from RCPT and LOAN)
* Current balance
* Overall stats about Contributions: % out of state, % within X (district or city), % within California 
* A break down of total contributions with a list: Donor Name | Donor Occupation | Donor City | Donation Amount | Date of Donation 
* A break down of total expenditures  by category

**Otherwise just get all the data and combine into this format**
1) Download the XSL/CSV files, add them to the git repository on a new branch
2) Combine the data into one XSL/CSV file per ballot measure/committee 
3) Turn the data in JSON

For reference take a look at PR #46

**Comment by phi-line** [comment]
Taking this

**Comment by aeevrubin** [comment]
So here's some things that I feel I should put out there:
A) There are no files uploaded for Measure S
B) For Measure T, only groups who support the measure have uploaded files
C) There are no files uploaded for Measure U
D) For Measure V, only groups who support the measure have uploaded files

**Comment by ychoy** [comment]
After talking with Open Oakland - learned that we don't just care about Form 460 (since that data only gets updated 2-3x a year), we also need to pay attention to:

Form 461 (filed by Independent Expenditure Committees.  These committees can fundraise for measures and/or candidates)
Form 496/497: Within 90 days of the election, contributions and expenditures over $1000 must be reported within 24 hours on form 496/497. Form 496/497 is tricky because items will be re-reported on the next Form 460.

If there is any data, we should try to get it uploaded.

**Comment by ychoy** [comment]
@phi-line, how is your progress? 

Please get the following files for Measures S, T, U, V by this Friday Nov 2:

- Form 460
- Form 460-A
- Form 461  
- Form 496/497

**Comment by ychoy** [comment]
Grace Lee @grle  and I are working on this issue.

**Comment by lenatran** [comment]
I got a file started for Measure T already, I can stop and work on issue 55 instead if you're going to work on it, lmk!

**Comment by lenatran** [comment]
@ychoy

**Comment by ychoy** [comment]
@lenatran Thank you for working on this. Sorry, I didn't see the message until now. I have the files for Measure STUV and one for General Purpose.  After a bit of research, we realized that we had to broaden the search (I'll explain more below). Some committees exist For/Against candidates and General Purpose (so they fundraise for more than one issue).

I do need help with the following - do you think you could get these uploaded by this Friday Nov 2 at 10:00pm? Priority to just get the single files. 

If you have time to combine them into each kind of related form, and then into a JSON file -- because the different forms have different headers, then that would be great.  

Whatever you are able to finish, please reference this issue and also comment which filers and Ballot Items you are able to address. Thank you!

Instructions: 

**Please organize files by directory:** 

- **Ballot Item (e.g. General Purpose)** 
-- Support (if Support) or Oppose (if it's Oppose)
---  **Committee/Filer Name** 
---- **Label each file with the data provided,** ex: 460_RecipientCommitteeCampaignStatement_1.31.2018_7.1.2017-12.31.2017.xls 

We need  *Form 460, Form 460-A,  Form 461, Form 496/497* for the following filers:

1) Go to https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/Search/SearchByBallotItem.aspx and select GENERAL, November 6, 2018, and General Purpose, and everything except Association of  Retired SJ Police Officers & Firefighters PAC: 
- [x] California Apartment Association Housing Solutions Committee,
- [x]  Registered Nurses Professional Association PAC
- [x] South Bay AFL-CIO Labor Council Committee on Political Education Sponsored by South Bay AFL-CIO Labor Council, 
- [x] South Bay AFL-CIO Labor Council Issues Account Sponsored by South Bay AFL-CIO Labor Council, 
- [x] The Silicon Valley Organization PAC,
- [x]  VietVoters PAC, 
- [x] Yes on C/No on B, Stop the Sprawl San Jose, Supported by Mayor Sam Liccardo 

2) Go to https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/Search/SearchByBallotItem.aspx and select GENERAL, 11/6/2018, and  COUNCILMEMBER-DISTRICT 7 and get the files from Filer Name 

- [x] Santa Clara County Government Attorneys' Association PAC

3) Go to https://www.southtechhosting.com/SanJoseCity/CampaignDocsWebRetrieval/Search/SearchByBallotItem.aspx and select  GENERAL, 11/6/2018, and  MAJOR DONOR 

- [x] Committee for Green Foothills Action

- [x] Garden City, Inc. DBA Casino M8trix

- [x] Gonsalves & Santucci Inc., dba The Conco Companies

- [x] The Health Trust

cc: @lilannie

**Comment by ychoy** [comment]
Hi @lenatran I addressed parts 2 and 3 above in PR #58, so the only data remaining we need is the remaining committees under General Purpose (part 1 in my previous message). Can you please let me know if you have time to address this today? Thanks!

**Comment by lenatran** [comment]
Hi @ychoy, I have a couple of hours available to work on this from now until 6pm, i will let you know my progress until then

**Comment by lenatran** [comment]
@ychoy I slacked you the files i compiled. i wasn't able to get it for all of the filers which i noted in the slack message

**Comment by ychoy** [comment]
Great thank you @lenatran
